
image: harrywagstaff/simbench

pipelines:
  default:
    - step: # ARM Versatile AB
        script:
          - \cp ./docker/arm-config ./arch/arm/Make.config 
          - ARCH=arm PLATFORM=versatile SIMBENCH_FAST=1 make
          - qemu-system-arm -machine versatileab -kernel out/arm/versatile/simbench -nographic -m 512 -display none -serial stdio -semihosting | host/host
    - step: # X86_64 Native
        script:
          - ARCH=x86_64 PLATFORM=native SIMBENCH_FAST=1 make
          - qemu-system-x86_64 -kernel out/x86_64/native/simbench -nographic | host/host
